
name: Run Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'  # Example: Run every minute    
  workflow_dispatch:  # Allows manual run from the GitHub Actions UI


concurrency:
  group: run-bot  # Group all "Run Bot" workflows into one group
  cancel-in-progress: true  # Cancel any previous runs that are still in progress
  
jobs:
  selenium-job-checker:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install selenium python-telegram-bot

    - name: Install Chrome 129.0.6668.71
      run: |
        # Download and install Chrome version 129.0.6668.71
        wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_129.0.6668.71-1_amd64.deb
        sudo dpkg -i google-chrome-stable_129.0.6668.71-1_amd64.deb || sudo apt-get --fix-broken install -y
        google-chrome --version  # Verify the installed Chrome version

    - name: Install ChromeDriver 129.0.6668.70
      run: |
        # Download and install ChromeDriver version 129.0.6668.70
        wget -N https://chromedriver.storage.googleapis.com/129.0.6668.70/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version  # Verify the installed ChromeDriver version
        
    - name: Run Selenium Job Checker
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: '7228218507'
      run: |
        Xvfb :99 -screen 0 1920x1080x16 &
        export DISPLAY=:99
        python Amazon_Bot.py

      

      
