
name: Run Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'  # Example: Run every minute    
  workflow_dispatch:  # Allows manual run from the GitHub Actions UI


concurrency:
  group: run-bot  # Group all "Run Bot" workflows into one group
  cancel-in-progress: true  # Cancel any previous runs that are still in progress
  
jobs:
  selenium-job-checker:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install selenium python-telegram-bot

    - name: Install Latest Stable Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        google-chrome --version  # Verify the installed Chrome version

    - name: Install Matching ChromeDriver
      run: |
        # Get the installed Chrome version
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)
        echo "Installed Chrome version: $CHROME_VERSION"

        # Fetch the corresponding ChromeDriver version
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION)
        echo "Matching ChromeDriver version: $CHROMEDRIVER_VERSION"

        # Download and install ChromeDriver
        wget -N https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv -f chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version  # Verify the installed ChromeDriver version

    - name: Run Selenium Job Checker
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: '7228218507'
      run: |
        Xvfb :99 -screen 0 1920x1080x16 &
        export DISPLAY=:99
        python Amazon_Bot.py

      

      
