name: Run Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'  # Example: Run every minute


concurrency:
  group: run-bot  # Group all "Run Bot" workflows into one group
  cancel-in-progress: true  # Cancel any previous runs that are still in progress
  
jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Access the BOT_TOKEN secret here
      run: python Amazon_Bot.py
