
name: Run Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'  # Example: Run every minute    
  workflow_dispatch:  # Allows manual run from the GitHub Actions UI


concurrency:
  group: run-bot  # Group all "Run Bot" workflows into one group
  cancel-in-progress: true  # Cancel any previous runs that are still in progress
  
jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        # Install Selenium, Telegram Bot, and WebDriverManager
        pip install selenium python-telegram-bot webdriver-manager

    - name: Run Selenium Test with WebDriverManager
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Use GitHub secrets for secure tokens
        CHAT_ID: '7228218507'
      run: |
        # Start Xvfb for headless Chrome execution
        Xvfb :99 -screen 0 1920x1080x16 &
        export DISPLAY=:99

        # Run the Selenium script     
        python Amazon_Bot.py

      

      
